config/routes.rb
Rails.application.routes.draw do
  resources :game_sessions do
    get :test_session, on: :collection

    resources :game, controller: "game_sessions/game"
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "game_sessions#new"
end

app/models/game_session.rb
class GameSession < ApplicationRecord
  class RolesSerializer
    def self.load(val)
      Array.wrap(val).map(&:constantize) if val
    end

    def self.dump(obj)
      Array.wrap(obj).map(&:name)
    end
  end

  has_many :players, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :nights, dependent: :destroy
  has_one  :active_night, -> { where(active: true) }, class_name: "Night"

  accepts_nested_attributes_for :players, allow_destroy: true, reject_if: :all_blank

  serialize :roles, coder: RolesSerializer

  validates :active_night, absence: true

  def deactive_night
    active_night&.update(active: false)
    association(:active_night).reset
  end
end

app/controllers/game_sessions/game_controller.rb
class GameSessions::GameController < ApplicationController
  include Wicked::Wizard

  before_action :set_game_session

  steps :preparation, :speaking, :vote, :night_action, :night_result

  def show
    case step
    when :preparation
      @players = @game_session.players
      @roles = @players.map(&:role)
      # @roles = @game_session.roles.map(&:new)
    when :speaking
      @players = @game_session.players.alive.shuffle
    when :vote
      @vote = @game_session.votes.build
      @players = @game_session.players.alive.shuffle
    when :night_action
      set_next_player
    when :night_result
      # @result = Action.last
    end
    render_wizard
  end

  def update
    case step
    when :vote
      @game_session.votes.create(vote_params)
    when :night_action
      player = @game_session.players.find(player_ability_params[:id])
      @result = player.use_ability(player_ability_params[:action_attributes])

      set_next_player unless @result
    end
    render_wizard @game_session, status: :ok
  end

  private

  def set_next_player
    queue = Rails.cache.fetch("night_#{active_night.id}", expires_in: 30.minutes) do
      game_service.generate_queue_for(active_night)
    end

    @player = queue.shift

    Rails.cache.write("night_#{active_night.id}", queue, expires_in: 20.minutes)
  end

  def active_night
    @active_night ||= @game_session.active_night || @game_session.create_active_night
  end

  def game_service
    Game::Service.new(@game_session)
  end

  def vote_params
    params.require(:vote).permit(:game_session_id, vote_candidates_attributes: [:candidate_id, voter_ids: []])
  end

  def player_ability_params
    params.require(:player).permit(:id, action_attributes: [:target_id, :guess, select_target_ids: [], kill_target_ids: []])
  end

  def set_game_session
    @game_session = GameSession.find(params[:game_session_id])
  end
end

app/controllers/game_sessions_controller.rb
class GameSessionsController < ApplicationController

  def new
    @game_session = GameSession.new
  end

  def create
    @game_session = Game::Operations::PrepareGameSession.call(game_session_params)

    respond_to do |format|
      if @game_session.save
        format.html { redirect_to game_session_game_path(@game_session, id: :preparation) }
        format.json { render :show, status: :created, location: @game_session }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game_session.errors, status: :unprocessable_entity }
      end
    end
  end

  def test_session
    game_session = GameSession.create

    FactoryBot.create_list(:player, 3, :mafia, game_session:)
    FactoryBot.create_list(:player, 3, :neutral, game_session:)
    FactoryBot.create_list(:player, 6, :civilian, game_session:)

    redirect_to game_session_game_path(game_session, id: :preparation)
  end

  private

    def game_session_params
      params.require(:game_session).permit(:title, players_attributes: [:id, :name, :_destroy])
    end
end

app/helpers/game_sessions_helper.rb
module GameSessionsHelper
end

app/views/game_sessions/_form.html.erb
<%= form_with(model: game_session, data: {
  controller: "nested-form",
  nested_form_wrapper_selector_value: ".nested-form-wrapper"
}) do |form| %>
  <div data-controller="dropdown">
    <div class="controls">
      <%= button_tag "Настройки игры", type: "button", class: "button-secondary", data: { action: "dropdown#toggle click@window->dropdown#hide" } %>
    </div>

    <div
      data-dropdown-target="menu"
      class="form-card hidden"
    >
      <div class="input-container">
        <%= form.number_field :discussion_time, class: "form-input" %>
        <%= form.label :discussion_time, "Время обсуждений", class: "form-label" %>
      </div>
    </div>
  </div>

  <template data-nested-form-target="template">
    <%= form.fields_for :players, Player.new, child_index: 'NEW_RECORD' do |player_fields| %>
      <%= render "players/form", f: player_fields %>
    <% end %>
  </template>

  <div class="form-card">
    <h2>Участники:</h2>
    <div data-nested-form-target="target"></div>
  </div>

  <div class="controls">
    <%= button_tag "Добавить игрока", type: "button", class: "button-primary", data: { action: "nested-form#add" } %>
    <%= button_tag "Начать игру", type: "submit", class: "button-secondary" %>
    <%= link_to "Сгенерировать тестовую сессию", test_session_game_sessions_path, class: "button-secondary" %>
  </div>
<% end %>

app/views/game_sessions/_game_session.html.erb
<div id="<%= dom_id game_session %>">
  <p>
    <strong>Title:</strong>
    <%= game_session.title %>
  </p>

  <div class="players">
    <%= render partial: "players/player", collection: game_session.players %>
  </div>
</div>

app/views/game_sessions/new.html.erb
<h1>New game session</h1>

<%= render "form", game_session: @game_session %>

app/views/game_sessions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @game_session %>

<div>
  <%= link_to "Edit this game session", edit_game_session_path(@game_session) %> |
  <%= link_to "Back to game sessions", game_sessions_path %>

  <%= button_to "Destroy this game session", @game_session, method: :delete %>
</div>